version: '3'

services:
  audiostorageservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    volumes:
      - "/home/keroosha/Music/:/app/Music"
    depends_on:
      - "db"
  db:
    environment:
      POSTGRES_PASSWORD: goaway359
    ports:
      - "5432:5432"