version: '3'

services:
  audiostorageservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  db:
    environment:
      POSTGRES_PASSWORD: goaway359
    ports:
      - "5432:5432"