version: '3'

services:
  audiostorageservice:
    image: audiostorageservice
    build:
      context: .
      dockerfile: AudioStorageService/Dockerfile

  db:
    image: postgres
    restart: always