version: '3'

services:
  audiostorageservice:
    image: audiostorageservice
    build:
      context: .
      dockerfile: AudioStorageService/Dockerfile
    links:
    - "PostgreSQL:db"

  PostgreSQL:
    image: postgres
    restart: always
    enviroment:
      POSTGRES_PASSWORD: goaway359